from ._async_client import AsyncDuckChat
from ._client import DuckChat
from ._exceptions import (
    APIError,
    ChallengeError,
    ConversationLimitError,
    DuckChatError,
    RateLimitError,
)
from ._models import (
    History,
    ImagePart,
    MODEL_ALIASES,
    Message,
    ModelType,
    Role,
    claude,
    claude_haiku,
    gpt4,
    gpt4o_mini,
    gpt5,
    gpt5_mini,
    gpt_oss,
    gpt_oss_120b,
    image_generation,
    llama,
    llama4_scout,
    mistral,
    mistral_small,
    model_supports_reasoning,
    model_supports_vision,
    resolve_effort,
    resolve_model,
)

__version__ = "0.4.0"

__all__ = [
    "DuckChat",
    "AsyncDuckChat",
    "ModelType",
    "Role",
    "Message",
    "History",
    "ImagePart",
    "DuckChatError",
    "ChallengeError",
    "RateLimitError",
    "ConversationLimitError",
    "APIError",
    "resolve_model",
    "resolve_effort",
    "model_supports_reasoning",
    "model_supports_vision",
    "MODEL_ALIASES",
    "gpt4",
    "gpt4o_mini",
    "gpt5",
    "gpt5_mini",
    "claude",
    "claude_haiku",
    "llama",
    "llama4_scout",
    "mistral",
    "mistral_small",
    "gpt_oss",
    "gpt_oss_120b",
    "image_generation",
    "__version__",
]
